name: covid_19_hackathon
description: Covid 19 hackathon for BuildforCOVID19 Global Online Hackathon

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.6.5
  esys_flutter_share: ^1.0.2
  google_fonts: ^0.3.10
  splashscreen: ^1.2.0
  image_picker: ^0.6.4
  geolocator: 5.0.1
  image: ^2.0.7
  flutter_svg:
  bubble_bottom_bar: ^1.2.0
  cached_network_image: 2.0.0
  uuid: 2.0.4
  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.6.1"

flutter:
  uses-material-design: true
  assets:
    - assets/news/covid1.jpeg
    - assets/news/
    - assets/images/upload.svg
    - assets/images/covid.jpg
    - assets/images/debate.jpg
    - assets/images/deathofachild.jpg
    - assets/images/borders.jpg
    - assets/images/yemen.jpg
    - assets/images/Test-1-square.jpg
    - assets/images/Test-1.jpg
    - assets/images/Logo_Color.png

